#pragma once

#include <stdbool.h>
#include <stdint.h>
#include "sysctl.h"
#include "hw_memmap.h"
#include "adc.h"
#include "uart.h"
#include "tm4c123gh6pm.h"
#include "hw_gpio.h"
#include "hw_types.h"
#include "pwm.h"
#include "gpio.h"
#include "pin_map.h"
#include "ADC_Helper.h"

void SetUpPWM0HZ(void);
void SetUpPWM82HZ(void);
void SetUpPWM87HZ(void);
void SetUpPWM92HZ(void);
void SetUpPWM98HZ(void);
void SetUpPWM104HZ(void);
void SetUpPWM110HZ(void);
void SetUpPWM117HZ(void);
void SetUpPWM123HZ(void);
void SetUpPWM131HZ(void);
void SetUpPWM139HZ(void);
void SetUpPWM147HZ(void);
void SetUpPWM156HZ(void);
void SetUpPWM165HZ(void);
void SetUpPWM175HZ(void);
void SetUpPWM185HZ(void);
void SetUpPWM196HZ(void);
void SetUpPWM208HZ(void);
void SetUpPWM220HZ(void);
void SetUpPWM233HZ(void);
void SetUpPWM247HZ(void);
void SetUpPWM261HZ(void);
void SetUpPWM277HZ(void);
void SetUpPWM294HZ(void);
void SetUpPWM311HZ(void);
void SetUpPWM330HZ(void);
void SetUpPWM349HZ(void);
void SetUpPWM369HZ(void);
void SetUpPWM392HZ(void);
void SetUpPWM415HZ(void);
void SetUpPWM440HZ(void);
void SetUpPWM466HZ(void);
void SetUpPWM493HZ(void);
void SetUpPWM523HZ(void);
void SetUpPWM554HZ(void);
void SetUpPWM587HZ(void);
void SetUpPWM622HZ(void);
void SetUpPWM659HZ(void);
void SetUpPWM698HZ(void);
void SetUpPWM740HZ(void);
void SetUpPWM784HZ(void);

void SetupPWM(void);
extern double DutyCycle;
