#pragma once

#include <stdbool.h>
#include <stdint.h>
#include "sysctl.h"
#include "hw_memmap.h"
#include "adc.h"
#include "uart.h"
#include "tm4c123gh6pm.h"
#include "hw_gpio.h"
#include "hw_types.h"
#include "pwm.h"
#include "gpio.h"
#include "pin_map.h"
#include "ADC_Helper.h"

void SetUpPWM0HZ(void);
void SetUpPWM82HZ(void);
void SetUpPWM87HZ(void);
void SetUpPWM92HZ(void);
void SetUpPWM98HZ(void);
void SetUpPWM104HZ(void);
void SetUpPWM110HZ(void);
void SetUpPWM117HZ(void);
void SetUpPWM123HZ(void);
void SetUpPWM131HZ(void);
void SetUpPWM139HZ(void);
void SetUpPWM147HZ(void);
void SetUpPWM156HZ(void);
void SetUpPWM165HZ(void);
void SetUpPWM175HZ(void);
void SetUpPWM185HZ(void);
void SetUpPWM196HZ(void);
void SetUpPWM208HZ(void);
void SetUpPWM300HZ(void);
void SetUpPWM400HZ(void);
void SetUpPWM500HZ(void);
void SetUpPWM600HZ(void);
void SetUpPWM700HZ(void);
void SetUpPWM800HZ(void);
void SetUpPWM900HZ(void);
void SetupPWM(void);
extern uint32_t DutyCycle;
